### ISSUE TITLE
使い方を教えていただけますでしょうか。

### ISSUE THREAD

**Issue by Name2889** [s1204IT/CPadGPlayEnabler#3]
こんにちは。チャレンジパッドNeo(TAB-A05-BD)を持っています。開発者modeをオンにして、adbにてapp等をインストールできます。但し、Google Playを何回インストールしても動いていません。どうやってGoogle Playをインストールするか教えていただけますでしょうか。
ありがとうございます。

「CPadGPlayEnabler.ps1」に書いた通りに手動でインストールしましたが、GooglePlayが動いていません。。。

お忙しいところ恐縮ですが、
よろしくお願いいたします。

**Comment by s1204IT** [comment]
こんばんは。
ご質問ありがとうございます、

Neo(CTX)/Next(CTZ) に関しては､ Googleサービスを完全に動作させる為の脆弱性が現状見つかっていないので、[microG](https://microg.org)で代替しています。
ですので、「**Google Playストア**」は動作しません。

一応､ バージョン **20**.x.x台 であれば起動はしますが、GmsCoreはmicroGである為 Googleアカウントは使えず、システムアプリでも無い為 サイレントインストールが出来ないので、パッケージ埋めの目的で「FakeStore」(microG提供)を入れています。

**Comment by Name2889** [comment]
こんにちは。
早急にご返信ありがとうございます。

承知いたしました。今はYoutubeなど全部をChromeにて使っています。残念ながらGSIなどカスタムROMをインストールもできません。試したいのですが、Backupもできないので。。。:)))
このタブレットのスペックはいいので、残念ですね。

よろしくお願いいたします。

**Comment by s1204IT** [comment]
YouTubeは[Vanced](https://github.com/cuynu/ytvanced/releases/tag/17.45.36)で代用できます。
最悪、[**Gspace**](https://gspaceteam.com/)内で代用する事も出来ます。

そもそもカスタムROM自体が存在しておらず、ブートローダーアンロックも出来ていないので、今後に期待です。
